server:
  port: 8088


spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotel/**
#            this is also one of them
#            - - Path=/hotel/**,/staffs/**
#            - path=/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**
#
#spring:
#  application:
#    name: API-GATEWAY
#
#  cloud:
#    gateway:
#    #  mvc:
#        routes:
#          - id: USER-SERVICE
#            uri: lb://USER-SERVICE
#            predicates:
#              - Paths=/users/**

#    cloud:
#
#          - id: USER-SERVICE
#            uri: lb://USER-SERVICE
#            predicates:
#              - Paths=/users/**


#ribbon:
#  ConnectTimeout: 5000
#  ReadTimeout: 60000
#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true

    service-url:
      defaultZone: http://localhost:8761/eureka


